# Generated by Django 3.2.6 on 2021-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('title', models.CharField(help_text="Enter listing's title", max_length=64, primary_key=True, serialize=False)),
                ('descrpt', models.TextField(help_text="Enter item's description")),
                ('beginningBid', models.IntegerField(help_text='Enter minimum price of item')),
                ('img', models.URLField(blank=True, help_text='*Optional* Enter image URL')),
                ('category', models.CharField(blank=True, help_text='*Optional* Enter listing category', max_length=64)),
            ],
        ),
    ]
