# Generated by Django 3.2.6 on 2021-08-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creator',
            field=models.CharField(default='None', help_text="Enter listing's creator:", max_length=64),
        ),
    ]
