# Generated by Django 3.2.6 on 2021-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210813_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text="Enter listing's title", max_length=64),
        ),
    ]
