# Generated by Django 3.2.6 on 2021-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highestBid',
            field=models.FloatField(default=None),
        ),
    ]
