# Generated by Django 3.2.6 on 2021-08-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_highestbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.FloatField(default=models.FloatField(help_text='Enter minimum price of item')),
        ),
    ]
