# Generated by Django 3.2.6 on 2021-08-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_highestbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('page', models.CharField(help_text='Add page title', max_length=64)),
                ('content', models.TextField(help_text='Enter content of comment')),
                ('commentor', models.CharField(help_text='Add name of watcher', max_length=64)),
            ],
        ),
    ]
