# Generated by Django 3.2.6 on 2021-09-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
