# Generated by Django 3.2.6 on 2021-10-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follow_followedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followedBy',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
