# Generated by Django 3.2.6 on 2021-08-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('page', models.CharField(help_text='Add page title', max_length=64)),
                ('watcher', models.CharField(help_text='Add name of watcher', max_length=64)),
            ],
        ),
    ]
